### ISSUE TITLE
Missing field_of_view.csv

### ISSUE THREAD

**Issue by leonard-psu** [ualsg/global-streetscapes#1]
Hello,

field_of_view.csv is missing from Hugging Face dataset repo  and is needed for

https://github.com/ualsg/global-streetscapes/blob/main/code/model_training/context/train_and_test.py

Lines 33 and 44
attr_dict = {'field_of_view': 'field_of_view.csv'

**Comment by Junguin** [comment]
Hi Leonard, thanks for raising this. It turns out we included this line by mistake. For field of view, the data was not so great so we resorted to calculating from metadata (referring to 'hFoV' and 'vFoV' in metadata_common_attributes.csv). We've removed the line from the code so it shouldn't cause more troubles now.
